worker_processes 1;
pid /tmp/tgl-nginx-test/nginx.pid;
error_log /tmp/tgl-nginx-test/error.log;

events {
    worker_connections 64;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    include /tmp/tgl-nginx-test/site.conf;
}
